const initialState = {
  groups: [],
  viewers: [],
  partners: [],
  goal: "",
  tags: [],
  wellbeingDomains: [],
  resources: [],
  meaning: "",
  benifits: [],
  subgoals: [],
  hindrances: [],
  checkInRecurrence: "",
  checkInTime: "",
  endDate: "",
  associatedHabits: [],
  enviroment: "",
  timeNeeded: "",
  timeNeededUnit: "",
  strategy: "",
  measurementType: "",
  measurementUnits: "",
  baseline: null,
  target: null,
  mainReward: ""
};
