const initialState = {
  active: false,
  groups: [],
  viewers: [],
  partners: [],
  habit: "",
  tags: [],
  wellbeingDomains: [],
  resources: [],
  meaning: "",
  benifits: [],
  badHabit: null,
  cue: "",
  recurrence: "",
  time: "",
  checkInRecurrence: "",
  checkInTime: "",
  endDate: "",
  associatedGoals: [],
  enviroment: "",
  timeNeeded: "",
  verification: "",
  strategy: "",
  measurementType: "",
  measurementUnits: "",
  measurement: null
};
